# Generated by Django 5.2.12 on 2026-03-31 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_membership'),
        ('tasks', '0002_taskactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'position']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'status', 'position'), name='unique_task_position_per_column'),
        ),
    ]
