# Generated by Django 5.2.12 on 2026-04-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_position_per_column',
        ),
    ]
