# Generated by Django 5.2.12 on 2026-04-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('reordered', 'Reordered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.task'),
        ),
    ]
